"use client";
import Link from "next/link";
import { CheckCircle2, FileText, ShieldCheck, Sparkles, Upload } from "lucide-react";
import FeatureCard from "@/components/FeatureCard";
import StepCard from "@/components/StepCard";

const footerLinks = [["Lease checklist", "/lease-review-checklist"], ["Guides", "/guides"], ["Students", "/students"], ["Landlords", "/landlords"], ["FAQ", "/faq"], ["Terms", "/terms"], ["Privacy", "/privacy"], ["Contact", "/contact"]];

export default function HomePage() {
  return <main className="min-h-screen bg-white text-left">
    <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><Link href="/" className="text-xl font-extrabold text-primary">The Lease Review</Link><Link href="/upload" className="rounded-full bg-primary px-5 py-2 font-bold text-white hover:bg-blue-700">Review my lease</Link></header>
    <section className="bg-primary-light px-6 py-20"><div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-2 md:items-center">
      <div className="flex flex-col items-start gap-6"><p className="font-bold text-primary">CLEARER LEASES. MORE CONFIDENT DECISIONS.</p><h1 className="text-4xl font-extrabold leading-tight text-slate-900 sm:text-6xl">Review your apartment lease before you sign</h1><p className="max-w-xl text-lg leading-relaxed text-slate-700">Upload a PDF or Word lease and receive a plain-English review of important clauses, possible concerns, and questions to raise.</p><Link href="/upload" className="rounded-full bg-primary px-8 py-4 text-lg font-bold text-white shadow-lg hover:bg-blue-700">Get your review for $19.99</Link><p className="text-sm text-slate-600">One-time payment · Files deleted after processing · Not legal advice</p></div>
      <div className="rounded-3xl border border-blue-100 bg-white p-8 shadow-xl"><FileText className="mb-5 h-12 w-12 text-primary" /><h2 className="text-2xl font-bold">Know what deserves a second look</h2><ul className="mt-5 space-y-3 text-slate-700">{["Security deposits and move-out charges", "Fees, utilities, and rent increases", "Early termination and renewal terms"].map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary" />{item}</li>)}</ul></div>
    </div></section>
    <section className="mx-auto max-w-6xl px-6 py-20"><h2 className="text-3xl font-extrabold">How it works</h2><div className="mt-8 grid gap-5 md:grid-cols-3"><StepCard step={1} icon={<Upload />} title="Upload your lease" description="Choose a PDF or Word document and enter your email." /><StepCard step={2} icon={<ShieldCheck />} title="Pay securely" description="A simple one-time payment of $19.99 through PayPal." /><StepCard step={3} icon={<Sparkles />} title="Get your review" description="Receive a structured summary of terms and issues to consider." /></div></section>
    <section className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-extrabold">Built for renters who want clarity</h2><div className="mt-8 grid gap-5 md:grid-cols-3"><FeatureCard icon={<FileText />} title="Plain English" description="Important terms presented in language you can understand." /><FeatureCard icon={<ShieldCheck />} title="Privacy-minded" description="Your uploaded document is deleted after processing." /><FeatureCard icon={<Sparkles />} title="Fast and focused" description="A practical starting point before you commit to a lease." /></div></div></section>
    <section className="mx-auto max-w-3xl px-6 py-20 text-center"><h2 className="text-3xl font-extrabold">One lease review, $19.99</h2><p className="mt-3 text-slate-700">No subscription. Upload your agreement and get a clear review before signing.</p><Link href="/upload" className="mt-7 inline-block rounded-full bg-primary px-8 py-4 font-bold text-white hover:bg-blue-700">Start your review</Link></section>
    <section className="bg-primary-light px-6 py-16"><div className="mx-auto max-w-3xl"><h2 className="text-3xl font-extrabold">Frequently asked questions</h2><div className="mt-6 space-y-4"><details className="rounded-xl bg-white p-5"><summary className="font-bold">Is this legal advice?</summary><p className="mt-2 text-slate-700">No. The Lease Review provides informational analysis, not legal advice or a lawyer-client relationship.</p></details><details className="rounded-xl bg-white p-5"><summary className="font-bold">What documents can I upload?</summary><p className="mt-2 text-slate-700">PDF, DOC, and DOCX residential lease documents are supported.</p></details></div><Link href="/faq" className="mt-5 inline-block font-bold text-primary">Read all FAQs →</Link></div></section>
    <footer className="bg-slate-900 px-6 py-10 text-sm text-slate-300"><div className="mx-auto flex max-w-6xl flex-wrap gap-x-5 gap-y-3"><span className="font-bold text-white">The Lease Review</span>{footerLinks.map(([label, href]) => <Link key={href} href={href} className="hover:text-white">{label}</Link>)}</div></footer>
  </main>;
}
